# Generated by Django 3.1.7 on 2022-06-12 17:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_id', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnumerationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_type_id', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('type_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.enumeration')),
            ],
        ),
        migrations.AddField(
            model_name='enumeration',
            name='enum_type_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.enumerationtype'),
        ),
        migrations.AddField(
            model_name='enumeration',
            name='parent_enum_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.enumeration'),
        ),
    ]
