# Generated by Django 3.1.7 on 2022-06-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.IntegerField()),
                ('N_S', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='North_South', to='ickoNavigator.enumerationtype')),
                ('W_E', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='West_East', to='ickoNavigator.enumerationtype')),
                ('targetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.target')),
            ],
        ),
    ]
