# Generated by Django 3.1.7 on 2022-06-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0002_gpsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('loadSkew', models.BooleanField()),
                ('loadPresent', models.BooleanField()),
                ('latchHealth', models.BooleanField()),
                ('loadHealth', models.BooleanField()),
                ('positionVerify', models.BooleanField()),
                ('spoofPresent', models.BooleanField()),
                ('gpsVerify', models.BooleanField()),
                ('incomingCall', models.BooleanField()),
                ('outgoingCall', models.BooleanField()),
                ('targetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.target')),
            ],
        ),
    ]
