# Generated by Django 3.1.7 on 2022-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0003_statusdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
