# Generated by Django 3.1.7 on 2022-06-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0004_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='longitude',
        ),
    ]
