# Generated by Django 3.1.7 on 2022-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0009_auto_20220613_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdata',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
