# Generated by Django 3.1.7 on 2022-06-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0010_auto_20220613_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='N_S',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='North_South', to='ickoNavigator.enumeration'),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='W_E',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='West_East', to='ickoNavigator.enumeration'),
        ),
    ]
