# Generated by Django 3.1.7 on 2022-07-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0011_auto_20220628_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampStart', models.FloatField()),
                ('callLength', models.IntegerField()),
                ('fromWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromWhom', to='ickoNavigator.target')),
                ('toWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toWhom', to='ickoNavigator.target')),
            ],
        ),
    ]
