# Generated by Django 3.1.7 on 2022-07-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0012_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeQueryMade', models.FloatField()),
                ('CallMade', models.BooleanField(default=False)),
                ('toWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toWhomQuery', to='ickoNavigator.target')),
            ],
        ),
    ]
