# Generated by Django 3.1.7 on 2022-07-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0015_auto_20220702_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadedTimestamp', models.IntegerField()),
                ('unloadedTimestamp', models.IntegerField()),
                ('fromLatitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fromLongitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('toLatitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('toLongitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('responsibleMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ickoNavigator.target')),
            ],
        ),
    ]
