# Generated by Django 3.1.7 on 2022-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0016_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='underLoadDuration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
