# Generated by Django 3.1.7 on 2022-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0017_loading_underloadduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='underLoadDuration',
            field=models.FloatField(blank=True),
        ),
    ]
