# Generated by Django 3.1.7 on 2022-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0018_auto_20220703_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='underLoadDuration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
