# Generated by Django 3.1.7 on 2022-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0019_auto_20220703_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='loadedTimestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='toLatitude',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='toLongitude',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='unloadedTimestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
