# Generated by Django 3.1.7 on 2022-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0020_auto_20220703_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='callLength',
            field=models.IntegerField(null=True),
        ),
    ]
