# Generated by Django 3.1.7 on 2022-07-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0023_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='fromSite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromSite', to='ickoNavigator.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loading',
            name='toSite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toSite', to='ickoNavigator.site'),
            preserve_default=False,
        ),
    ]
