# Generated by Django 3.1.7 on 2022-07-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ickoNavigator', '0024_auto_20220714_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='pavedDistance',
            field=models.IntegerField(null=True),
        ),
    ]
